### ISSUE TITLE
Flowable 6.6 - Missing checkbox "terminate all" for end terminate event 

### ISSUE THREAD

**Issue by olekkosma** [flowable/flowable-engine#2667]
**Describe the bug**
Missing checkbox. I cant use it via UI.

**Expected behavior**
Checkbox should be visible.

**Code**
-

**Additional context**
In 6.5 checkbox was visible.
As image shows:
![image](https://user-images.githubusercontent.com/16398511/97429601-f036d680-1917-11eb-9c18-2162bc766e1d.png)

**Comment by filiphr** [comment]
Thanks for reporting this @olekkosma. I am fairly certain that PR #2662 by @jaam is the fix for this.

**Comment by jaam** [comment]
Yes, with my PR should be fixed. Basically the bug affects all checkboxes present in modeler.

**Comment by tijsrademakers** [comment]
Thanks for reporting the issue, merged the PR from @jaam so should be fixed now

**Comment by douglascrp** [comment]
> Yes, with my PR should be fixed. Basically the bug affects all checkboxes present in modeler.

Hey @jaam 
Unfortunately, it seems that it is not the case with the Exclusive Gateway Default flow property, as it is still not rendered, as I mentioned at #2661
